import {
  account,
  authRelations,
  rateLimit,
  session,
  user,
  verification,
} from "@db/schema/auth";
import {
  courseAssessmentDefaults,
  curriculumAssessmentOverrides,
  curriculumCourses,
  curriculumDocuments,
  curricula,
} from "@db/schema/curriculum";
import {
  identityAccounts,
  identifierReservations,
  identifierSequences,
  permissions,
  programHeads,
  roleConflicts,
  rolePermissions,
  roles,
  securityEvents,
  userRoles,
  userScopes,
} from "@db/schema/identity";
import {
  assignmentFiles,
  assignmentSubmissions,
  assignments,
  forumAttachments,
  forumPosts,
  forumThreads,
  learningMaterials,
  materialFiles,
  submissionFiles,
} from "@db/schema/lms";
import {
  academicPeriods,
  academicYears,
  cohorts,
  courses,
  importJobs,
  importRows,
  lecturers,
  students,
  studyPrograms,
} from "@db/schema/master-data";
import {
  auditLogs,
  backgroundJobs,
  fileObjects,
  idempotencyKeys,
  notifications,
  outboxEvents,
} from "@db/schema/platform";
import {
  classEnrollments,
  classMappingJobs,
  classMeetings,
  classSections,
  examSchedules,
  lecturerAvailabilities,
  scheduleApprovals,
  scheduleChangeRequests,
  scheduleConflicts,
  scheduleDrafts,
  scheduleRevisions,
  scheduleSlots,
  teachingAssignments,
} from "@db/schema/scheduling";
import {
  gradeScaleEntries,
  gradeScaleSets,
  policyActivationHistories,
  settingDefinitions,
  settingValues,
  settingVersions,
} from "@db/schema/settings";
import {
  studyPlanGenerationJobs,
  studyPlanHistories,
  studyPlanItems,
  studyPlans,
} from "@db/schema/study-plan";
import { defineRelations } from "drizzle-orm";

const schema = {
  academicPeriods,
  academicYears,
  account,
  assignmentFiles,
  assignmentSubmissions,
  assignments,
  auditLogs,
  backgroundJobs,
  classEnrollments,
  classMappingJobs,
  classMeetings,
  classSections,
  cohorts,
  courseAssessmentDefaults,
  courses,
  curricula,
  curriculumAssessmentOverrides,
  curriculumCourses,
  curriculumDocuments,
  examSchedules,
  fileObjects,
  forumAttachments,
  forumPosts,
  forumThreads,
  gradeScaleEntries,
  gradeScaleSets,
  idempotencyKeys,
  identifierReservations,
  identifierSequences,
  identityAccounts,
  importJobs,
  importRows,
  learningMaterials,
  lecturerAvailabilities,
  lecturers,
  materialFiles,
  notifications,
  outboxEvents,
  permissions,
  policyActivationHistories,
  programHeads,
  rateLimit,
  roleConflicts,
  rolePermissions,
  roles,
  scheduleApprovals,
  scheduleChangeRequests,
  scheduleConflicts,
  scheduleDrafts,
  scheduleRevisions,
  scheduleSlots,
  securityEvents,
  session,
  settingDefinitions,
  settingValues,
  settingVersions,
  students,
  studyPlanGenerationJobs,
  studyPlanHistories,
  studyPlanItems,
  studyPlans,
  studyPrograms,
  submissionFiles,
  teachingAssignments,
  user,
  userRoles,
  userScopes,
  verification,
};

export const relations = {
  ...defineRelations(schema),
  ...authRelations,
};
