import {
  account,
  authRelations,
  rateLimit,
  session,
  user,
  verification,
} from "@db/schema/auth";
import {
  courseAssessmentDefaults,
  curriculumAssessmentOverrides,
  curriculumCourses,
  curriculumDocuments,
  curricula,
} from "@db/schema/curriculum";
import {
  identityAccounts,
  identifierReservations,
  identifierSequences,
  permissions,
  programHeads,
  roleConflicts,
  rolePermissions,
  roles,
  securityEvents,
  userRoles,
  userScopes,
} from "@db/schema/identity";
import {
  academicPeriods,
  academicYears,
  cohorts,
  courses,
  importJobs,
  importRows,
  lecturers,
  students,
  studyPrograms,
} from "@db/schema/master-data";
import {
  auditLogs,
  backgroundJobs,
  fileObjects,
  idempotencyKeys,
  notifications,
  outboxEvents,
} from "@db/schema/platform";
import {
  gradeScaleEntries,
  gradeScaleSets,
  policyActivationHistories,
  settingDefinitions,
  settingValues,
  settingVersions,
} from "@db/schema/settings";
import { defineRelations } from "drizzle-orm";

const schema = {
  academicPeriods,
  academicYears,
  account,
  auditLogs,
  backgroundJobs,
  cohorts,
  courseAssessmentDefaults,
  courses,
  curricula,
  curriculumAssessmentOverrides,
  curriculumCourses,
  curriculumDocuments,
  fileObjects,
  gradeScaleEntries,
  gradeScaleSets,
  idempotencyKeys,
  identifierReservations,
  identifierSequences,
  identityAccounts,
  importJobs,
  importRows,
  lecturers,
  notifications,
  outboxEvents,
  permissions,
  policyActivationHistories,
  programHeads,
  rateLimit,
  roleConflicts,
  rolePermissions,
  roles,
  securityEvents,
  session,
  settingDefinitions,
  settingValues,
  settingVersions,
  students,
  studyPrograms,
  user,
  userRoles,
  userScopes,
  verification,
};

export const relations = {
  ...defineRelations(schema),
  ...authRelations,
};
