export {
  account,
  authRelations,
  rateLimit,
  session,
  user,
  verification,
} from "@db/schema/auth";
export {
  identityAccounts,
  identityAccountStatuses,
  identityTypes,
  identifierReservations,
  identifierSequences,
  identityRelations,
  permissions,
  programHeads,
  provisioningStatuses,
  roleConflicts,
  roleKeys,
  rolePermissions,
  roles,
  scopeTypes,
  securityEvents,
  userRoles,
  userScopes,
} from "@db/schema/identity";
export {
  auditLogs,
  backgroundJobs,
  fileObjects,
  idempotencyKeys,
  notifications,
  outboxEvents,
} from "@db/schema/platform";
export {
  gradeScaleEntries,
  gradeScaleSets,
  policyActivationHistories,
  settingCategories,
  settingDefinitions,
  settingScopeTypes,
  settingValueTypes,
  settingValues,
  settingVersions,
} from "@db/schema/settings";
export {
  academicPeriodStatuses,
  academicPeriodTerms,
  academicPeriods,
  academicStatuses,
  academicYears,
  cohorts,
  courses,
  identifierTypes,
  identifierUsages,
  importEntityTypes,
  importJobs,
  importRowCommitStatuses,
  importRows,
  importRowStatuses,
  importStatuses,
  lecturers,
  masterDataStatuses,
  masterProvisioningStatuses,
  rooms,
  students,
  studyPrograms,
} from "@db/schema/master-data";
export {
  courseAssessmentDefaults,
  curriculumAssessmentOverrides,
  curriculumCourseTypes,
  curriculumCourses,
  curriculumDocuments,
  curricula,
  curriculumStatuses,
} from "@db/schema/curriculum";
export {
  studyPlanGenerationJobs,
  studyPlanHistories,
  studyPlanHistoryActions,
  studyPlanItems,
  studyPlanModes,
  studyPlans,
  studyPlanStatuses,
} from "@db/schema/study-plan";
