export {
  account,
  authRelations,
  rateLimit,
  session,
  user,
  verification,
} from "@db/schema/auth";
export {
  emailChangeRequests,
  identityAccounts,
  identityAccountStatuses,
  identityTypes,
  identifierReservations,
  identifierSequences,
  identityRelations,
  permissions,
  programHeads,
  provisioningStatuses,
  roleConflicts,
  roleKeys,
  rolePermissions,
  roles,
  scopeTypes,
  securityEvents,
  userRoles,
  userScopes,
} from "@db/schema/identity";
export {
  auditLogs,
  backgroundJobs,
  fileObjects,
  idempotencyKeys,
  notifications,
  outboxEvents,
} from "@db/schema/platform";
export {
  gradeScaleEntries,
  gradeScaleSets,
  policyActivationHistories,
  settingCategories,
  settingDefinitions,
  settingScopeTypes,
  settingValueTypes,
  settingValues,
  settingVersions,
} from "@db/schema/settings";
export {
  academicPeriodStatuses,
  academicPeriodTerms,
  academicPeriods,
  academicStatuses,
  academicYears,
  cohorts,
  courses,
  identifierTypes,
  identifierUsages,
  importEntityTypes,
  importJobs,
  importRowCommitStatuses,
  importRows,
  importRowStatuses,
  importStatuses,
  lecturers,
  masterDataStatuses,
  masterProvisioningStatuses,
  rooms,
  students,
  studyPrograms,
} from "@db/schema/master-data";
export {
  courseAssessmentDefaults,
  curriculumAssessmentOverrides,
  curriculumCourseTypes,
  curriculumCourses,
  curriculumDocuments,
  curricula,
  curriculumStatuses,
} from "@db/schema/curriculum";
export {
  studyPlanGenerationJobs,
  studyPlanHistories,
  studyPlanHistoryActions,
  studyPlanItems,
  studyPlanModes,
  studyPlans,
  studyPlanStatuses,
} from "@db/schema/study-plan";
export {
  assignmentFiles,
  assignmentSubmissionStatuses,
  assignmentSubmissions,
  assignments,
  forumAttachments,
  forumPosts,
  forumThreadStatuses,
  forumThreads,
  learningContentStatuses,
  learningMaterials,
  materialFiles,
  submissionFiles,
} from "@db/schema/lms";
export {
  attendanceAdjustments,
  attendanceCaptureAttempts,
  attendanceEvidences,
  attendanceEvidenceTypes,
  attendanceGenerationJobs,
  attendanceJobStatuses,
  attendanceParticipantTypes,
  attendanceRecords,
  attendanceRequests,
  attendanceRequestStatuses,
  attendanceReviewDecisions,
  attendanceReviewLogs,
  attendanceSessions,
  attendanceStatuses,
} from "@db/schema/attendance";
export {
  classEnrollments,
  classMappingJobs,
  classMeetings,
  classSections,
  classSectionStatuses,
  examSchedules,
  lecturerAvailabilities,
  scheduleApprovals,
  scheduleChangeRequests,
  scheduleChangeRequestStatuses,
  scheduleConflicts,
  scheduleConflictSeverities,
  scheduleDrafts,
  scheduleDraftStatuses,
  scheduleModalities,
  scheduleRevisions,
  scheduleSlots,
  teachingAssignments,
} from "@db/schema/scheduling";
export {
  classGradeComponents,
  finalGradeSnapshots,
  gradeAdjustments,
  gradePublications,
  gradeStatuses,
  gradeSubmissionBatches,
  studentComponentScores,
  studyResultSnapshots,
  transcriptEntries,
} from "@db/schema/grades";
